### ISSUE TITLE
Add support for more emulators like SMS plus and snes9x.

### ISSUE THREAD

**Issue by nl255** [NekoMichi/DinguxSaveSync#1]
I noticed that neither SMS Plus or Snes9x are supported and it would be nice to be able to backup their save data as well.  SMS Plus saves can be stored in either .smsplus or .sms_sdl (in the sram/state subfolders) and snes9x in .snes9x/(in the spc and sram subfolders).

I would also like to see support for swanemu (.swanemu,  eeprom/sstates), Temper (.temper, bram/save_states), and ohboy (.ohboy/saves).

**Comment by NekoMichi** [comment]
Thanks for bringing this to my attention, I will be adding support for SMS Plus, Snes9x, SwanEmu, Temper, and OhBoy in the next update.

**Comment by NekoMichi** [comment]
Support for the emulators has been added in version 2.3.
